# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ROHlen <- function(pA, chr, pos, beg, end, minROHLength, minDistHet, maxGapLength, NAsAreHet) {
    .Call(`_gaston_ROHlen`, pA, chr, pos, beg, end, minROHLength, minDistHet, maxGapLength, NAsAreHet)
}

ROHs <- function(pA, chr, pos, beg, end, minROHLength, minDistHet, maxGapLength, NAsAreHet) {
    .Call(`_gaston_ROHs`, pA, chr, pos, beg, end, minROHLength, minDistHet, maxGapLength, NAsAreHet)
}

alleles_recoding <- function(L) {
    .Call(`_gaston_alleles_recoding`, L)
}

alleles_duplicated <- function(snps, D) {
    .Call(`_gaston_alleles_duplicated`, snps, D)
}

duplicated_remove <- function(x, D, keep, flip, newm, na, incomp) {
    .Call(`_gaston_duplicated_remove`, x, D, keep, flip, newm, na, incomp)
}

AIREML1_nofix <- function(Y, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau, max_iter, eps, verbose, theta0, start_theta, get_P) {
    .Call(`_gaston_AIREML1_nofix`, Y, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau, max_iter, eps, verbose, theta0, start_theta, get_P)
}

AIREML1_contrast <- function(Y, X, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau, max_iter, eps, verbose, theta0, start_theta, get_P) {
    .Call(`_gaston_AIREML1_contrast`, Y, X, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau, max_iter, eps, verbose, theta0, start_theta, get_P)
}

AIREML1 <- function(Y, X, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau, max_iter, eps, verbose, theta0, start_theta, get_P) {
    .Call(`_gaston_AIREML1`, Y, X, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau, max_iter, eps, verbose, theta0, start_theta, get_P)
}

AIREML1_logit_nofix <- function(Y, K_, constraint, min_tau, max_iter, eps, verbose, tau0, start_tau, get_P, EM) {
    .Call(`_gaston_AIREML1_logit_nofix`, Y, K_, constraint, min_tau, max_iter, eps, verbose, tau0, start_tau, get_P, EM)
}

AIREML1_logit <- function(Y, X, K_, constraint, min_tau, max_iter, eps, verbose, tau0, beta0, start_tau, start_beta, get_P, EM) {
    .Call(`_gaston_AIREML1_logit`, Y, X, K_, constraint, min_tau, max_iter, eps, verbose, tau0, beta0, start_tau, start_beta, get_P, EM)
}

AIREMLn_logit_nofix <- function(Y, K_, constraint, min_tau_, max_iter, eps, verbose, tau0, start_tau, get_P, EM) {
    .Call(`_gaston_AIREMLn_logit_nofix`, Y, K_, constraint, min_tau_, max_iter, eps, verbose, tau0, start_tau, get_P, EM)
}

AIREMLn_logit <- function(Y, X, K_, constraint, min_tau_, max_iter, eps, verbose, tau0, beta0, start_tau, start_beta, get_P, EM) {
    .Call(`_gaston_AIREMLn_logit`, Y, X, K_, constraint, min_tau_, max_iter, eps, verbose, tau0, beta0, start_tau, start_beta, get_P, EM)
}

AIREMLn_nofix <- function(Y, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau_, max_iter, eps, verbose, theta_, start_theta, get_P) {
    .Call(`_gaston_AIREMLn_nofix`, Y, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau_, max_iter, eps, verbose, theta_, start_theta, get_P)
}

AIREMLn_contrast <- function(Y, X, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau_, max_iter, eps, verbose, theta_, start_theta, get_P) {
    .Call(`_gaston_AIREMLn_contrast`, Y, X, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau_, max_iter, eps, verbose, theta_, start_theta, get_P)
}

AIREMLn <- function(Y, X, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau_, max_iter, eps, verbose, theta_, start_theta, get_P) {
    .Call(`_gaston_AIREMLn`, Y, X, K_, EMsteps, EMsteps_fail, EM_alpha, constraint, min_s2, min_tau_, max_iter, eps, verbose, theta_, start_theta, get_P)
}

logistic <- function(Y, X, eps) {
    .Call(`_gaston_logistic`, Y, X, eps)
}

GWAS_lm_quanti <- function(pA, mu, Y, Q_, beg, end) {
    .Call(`_gaston_GWAS_lm_quanti`, pA, mu, Y, Q_, beg, end)
}

GWAS_lmm_lrt <- function(pA, mu, Y, X, p, Sigma, U, beg, end, tol) {
    .Call(`_gaston_GWAS_lmm_lrt`, pA, mu, Y, X, p, Sigma, U, beg, end, tol)
}

GWAS_lmm_wald <- function(pA, mu, Y, X, p, Sigma, U, beg, end, tol) {
    .Call(`_gaston_GWAS_lmm_wald`, pA, mu, Y, X, p, Sigma, U, beg, end, tol)
}

GWAS_lmm_score <- function(pA, PY, P, mu, beg, end) {
    .Call(`_gaston_GWAS_lmm_score`, pA, PY, P, mu, beg, end)
}

GWAS_lmm_score_f <- function(pA, PY, P, mu, beg, end) {
    .Call(`_gaston_GWAS_lmm_score_f`, pA, PY, P, mu, beg, end)
}

GWAS_logit_wald_f <- function(pA, mu, Y, X, beg, end, tol) {
    .Call(`_gaston_GWAS_logit_wald_f`, pA, mu, Y, X, beg, end, tol)
}

GWAS_logitmm_wald_f <- function(pA, mu, Y, X, K, beg, end, tol) {
    .Call(`_gaston_GWAS_logitmm_wald_f`, pA, mu, Y, X, K, beg, end, tol)
}

hwe <- function(N0, N1, N2) {
    .Call(`_gaston_hwe`, N0, N1, N2)
}

hwe_chi <- function(N0, N1, N2) {
    .Call(`_gaston_hwe_chi`, N0, N1, N2)
}

isnullptr <- function(pointer) {
    .Call(`_gaston_isnullptr`, pointer)
}

ld_clump <- function(pA, mu, sd, threshold, pos, chr, max_dist, order) {
    .Call(`_gaston_ld_clump`, pA, mu, sd, threshold, pos, chr, max_dist, order)
}

fit_diago <- function(Y, X, p_, Sigma, U, min_h2, max_h2, tol, verbose, brent) {
    .Call(`_gaston_fit_diago`, Y, X, p_, Sigma, U, min_h2, max_h2, tol, verbose, brent)
}

fit_diago_nocovar <- function(Y, p_, Sigma, U, min_h2, max_h2, tol, verbose, brent) {
    .Call(`_gaston_fit_diago_nocovar`, Y, p_, Sigma, U, min_h2, max_h2, tol, verbose, brent)
}

diago_full_likelihood1 <- function(h2, p, Y, X, Sigma, U) {
    .Call(`_gaston_diago_full_likelihood1`, h2, p, Y, X, Sigma, U)
}

diago_full_likelihood2 <- function(tau, s2, p, Y, X, Sigma, U) {
    .Call(`_gaston_diago_full_likelihood2`, tau, s2, p, Y, X, Sigma, U)
}

diago_full_likelihood1_nocovar <- function(h2, p, Y, Sigma, U) {
    .Call(`_gaston_diago_full_likelihood1_nocovar`, h2, p, Y, Sigma, U)
}

diago_full_likelihood2_nocovar <- function(tau, s2, p, Y, Sigma, U) {
    .Call(`_gaston_diago_full_likelihood2_nocovar`, tau, s2, p, Y, Sigma, U)
}

diago_likelihood1 <- function(h2, p, Y, X, Sigma, U) {
    .Call(`_gaston_diago_likelihood1`, h2, p, Y, X, Sigma, U)
}

diago_likelihood2 <- function(tau, s2, p, Y, X, Sigma, U) {
    .Call(`_gaston_diago_likelihood2`, tau, s2, p, Y, X, Sigma, U)
}

diago_likelihood1_nocovar <- function(h2, p, Y, Sigma, U) {
    .Call(`_gaston_diago_likelihood1_nocovar`, h2, p, Y, Sigma, U)
}

diago_likelihood2_nocovar <- function(tau, s2, p, Y, Sigma, U) {
    .Call(`_gaston_diago_likelihood2_nocovar`, tau, s2, p, Y, Sigma, U)
}

logp_thinning <- function(logp, step) {
    .Call(`_gaston_logp_thinning`, logp, step)
}

read_bed_file <- function(filename, n_ind, n_snp) {
    .Call(`_gaston_read_bed_file`, filename, n_ind, n_snp)
}

write_bed_file <- function(p_A, filename) {
    invisible(.Call(`_gaston_write_bed_file`, p_A, filename))
}

bind_inds2 <- function(L, flip) {
    .Call(`_gaston_bind_inds2`, L, flip)
}

bind_snps <- function(L) {
    .Call(`_gaston_bind_snps`, L)
}

new_matrix4 <- function(nrow, ncol) {
    .Call(`_gaston_new_matrix4`, nrow, ncol)
}

as_matrix4 <- function(A) {
    .Call(`_gaston_as_matrix4`, A)
}

raw_as_matrix4 <- function(A) {
    .Call(`_gaston_raw_as_matrix4`, A)
}

m4_as012 <- function(pA) {
    .Call(`_gaston_m4_as012`, pA)
}

m4_as_scaled_matrix_p <- function(pA, p) {
    .Call(`_gaston_m4_as_scaled_matrix_p`, pA, p)
}

m4_as_scaled_matrix_mu_sigma <- function(pA, mu, sigma) {
    .Call(`_gaston_m4_as_scaled_matrix_mu_sigma`, pA, mu, sigma)
}

nsnps <- function(p_A) {
    .Call(`_gaston_nsnps`, p_A)
}

ninds <- function(p_A) {
    .Call(`_gaston_ninds`, p_A)
}

cat_matrix4 <- function(p_A) {
    invisible(.Call(`_gaston_cat_matrix4`, p_A))
}

fill_line <- function(p_A, li, w) {
    invisible(.Call(`_gaston_fill_line`, p_A, li, w))
}

extract_inds_bool <- function(pA, w) {
    .Call(`_gaston_extract_inds_bool`, pA, w)
}

extract_inds_indices <- function(pA, w) {
    .Call(`_gaston_extract_inds_indices`, pA, w)
}

extract_snps_bool <- function(pA, w) {
    .Call(`_gaston_extract_snps_bool`, pA, w)
}

extract_snps_indices <- function(pA, w) {
    .Call(`_gaston_extract_snps_indices`, pA, w)
}

Kinship <- function(p_A, mu, w, chunk) {
    .Call(`_gaston_Kinship`, p_A, mu, w, chunk)
}

Kinship_w <- function(p_A, mu, w, snps, chunk) {
    .Call(`_gaston_Kinship_w`, p_A, mu, w, snps, chunk)
}

Kinship_pw <- function(p_A, p, snps, dominance, chunk) {
    .Call(`_gaston_Kinship_pw`, p_A, p, snps, dominance, chunk)
}

LD <- function(p_A, mu, sd, c1, c2) {
    .Call(`_gaston_LD`, p_A, mu, sd, c1, c2)
}

LD_chunk <- function(p_A, mu, sd, c1, c2, d1, d2) {
    .Call(`_gaston_LD_chunk`, p_A, mu, sd, c1, c2, d1, d2)
}

LD_p <- function(p_A, p, c1, c2) {
    .Call(`_gaston_LD_p`, p_A, p, c1, c2)
}

LD_chunk_p <- function(p_A, p, c1, c2, d1, d2) {
    .Call(`_gaston_LD_chunk_p`, p_A, p, c1, c2, d1, d2)
}

ld_thin_left <- function(pA, mu, sd, threshold, pos, chr, max_dist, beg, end, w_) {
    .Call(`_gaston_ld_thin_left`, pA, mu, sd, threshold, pos, chr, max_dist, beg, end, w_)
}

ld_thin_random <- function(pA, mu, sd, threshold, pos, chr, max_dist, beg, end, w_) {
    .Call(`_gaston_ld_thin_random`, pA, mu, sd, threshold, pos, chr, max_dist, beg, end, w_)
}

ld_thin_right <- function(pA, mu, sd, threshold, pos, chr, max_dist, beg, end, w_) {
    .Call(`_gaston_ld_thin_right`, pA, mu, sd, threshold, pos, chr, max_dist, beg, end, w_)
}

m4_loading_to_pc_ms <- function(p_A, mu, sd, v) {
    .Call(`_gaston_m4_loading_to_pc_ms`, p_A, mu, sd, v)
}

m4_loading_to_pc_p <- function(p_A, p, v) {
    .Call(`_gaston_m4_loading_to_pc_p`, p_A, p, v)
}

m4_pc_to_loading_ms <- function(p_A, mu, sd, v) {
    .Call(`_gaston_m4_pc_to_loading_ms`, p_A, mu, sd, v)
}

m4_pc_to_loading_p <- function(p_A, p, v) {
    .Call(`_gaston_m4_pc_to_loading_p`, p_A, p, v)
}

read_vcf2 <- function(filename, max_snps, get_info) {
    .Call(`_gaston_read_vcf2`, filename, max_snps, get_info)
}

read_vcf_filtered <- function(filename, POS, max_snps, get_info) {
    .Call(`_gaston_read_vcf_filtered`, filename, POS, max_snps, get_info)
}

invert_snp_coding <- function(p_A, snp) {
    invisible(.Call(`_gaston_invert_snp_coding`, p_A, snp))
}

snp_hz_to_na <- function(p_A, snp) {
    invisible(.Call(`_gaston_snp_hz_to_na`, p_A, snp))
}

set_snp_to_na <- function(p_A, snp) {
    invisible(.Call(`_gaston_set_snp_to_na`, p_A, snp))
}

geno_stats <- function(p_A, chr_x, chr_y, chr_mt, sexf) {
    .Call(`_gaston_geno_stats`, p_A, chr_x, chr_y, chr_mt, sexf)
}

geno_stats_snps <- function(p_A, chr_xy, sexf) {
    .Call(`_gaston_geno_stats_snps`, p_A, chr_xy, sexf)
}

geno_stats_inds <- function(p_A, chr_x, chr_y, chr_mt) {
    .Call(`_gaston_geno_stats_inds`, p_A, chr_x, chr_y, chr_mt)
}

transpose_m4 <- function(p_A) {
    .Call(`_gaston_transpose_m4`, p_A)
}

manhattan_thinning <- function(x, y, mx, my) {
    .Call(`_gaston_manhattan_thinning`, x, y, mx, my)
}

chol_inverse <- function(X) {
    .Call(`_gaston_chol_inverse`, X)
}

pre_likelihood <- function(Y, X, K_, h2) {
    .Call(`_gaston_pre_likelihood`, Y, X, K_, h2)
}

pre_likelihood_nofix <- function(Y, K_, h2) {
    .Call(`_gaston_pre_likelihood_nofix`, Y, K_, h2)
}

random_ortho <- function(n) {
    .Call(`_gaston_random_ortho`, n)
}

re_likelihood <- function(Y, X, K_, theta) {
    .Call(`_gaston_re_likelihood`, Y, X, K_, theta)
}

re_likelihood_nofix <- function(Y, K_, theta) {
    .Call(`_gaston_re_likelihood_nofix`, Y, K_, theta)
}

which_duplicated_chr_pos <- function(Chr, Pos) {
    .Call(`_gaston_which_duplicated_chr_pos`, Chr, Pos)
}

which_duplicated_chr_pos_alleles <- function(Chr, Pos, AL1, AL2) {
    .Call(`_gaston_which_duplicated_chr_pos_alleles`, Chr, Pos, AL1, AL2)
}

which_duplicated_id <- function(Id) {
    .Call(`_gaston_which_duplicated_id`, Id)
}

which_duplicated_id_chr_pos <- function(Id, Chr, Pos) {
    .Call(`_gaston_which_duplicated_id_chr_pos`, Id, Chr, Pos)
}

which_duplicated_id_chr_pos_alleles <- function(Id, Chr, Pos, AL1, AL2) {
    .Call(`_gaston_which_duplicated_id_chr_pos_alleles`, Id, Chr, Pos, AL1, AL2)
}

SNPmatch <- function(x, table) {
    .Call(`_gaston_SNPmatch`, x, table)
}

